/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mulesoft;
import java.sql.Connection;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author harsh
 */
public class Movies extends javax.swing.JFrame {

    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        edtActress = new javax.swing.JTextField();
        edtMovie = new javax.swing.JTextField();
        edtActor = new javax.swing.JTextField();
        edtDirector = new javax.swing.JTextField();
        edtRelease = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnFetch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 150, 160), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Movies");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 183, 72));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 760, -1));

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtActress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtActress.setText("Enter Actress Name");
        edtActress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtActressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtActressFocusLost(evt);
            }
        });
        jPanel4.add(edtActress, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 230, 39));

        edtMovie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtMovie.setText("Enter Movie Name");
        edtMovie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtMovieFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtMovieFocusLost(evt);
            }
        });
        jPanel4.add(edtMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 230, 39));

        edtActor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtActor.setText("Enter Actor Name");
        edtActor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtActorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtActorFocusLost(evt);
            }
        });
        jPanel4.add(edtActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 20, 230, 39));

        edtDirector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtDirector.setText("Enter Director Name");
        edtDirector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtDirectorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtDirectorFocusLost(evt);
            }
        });
        jPanel4.add(edtDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 65, 230, 39));

        edtRelease.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtRelease.setText("Enter Release Year");
        edtRelease.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtReleaseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtReleaseFocusLost(evt);
            }
        });
        jPanel4.add(edtRelease, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 65, 230, 39));

        submit.setBackground(new java.awt.Color(51, 255, 0));
        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 153, 102));
        submit.setText("Insert");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel4.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 65, 170, 39));

        jPanel3.add(jPanel4, "card2");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 760, 130));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Movie", "Actor", "Actress", "Director", "Year Of Release"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(10);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 730, 200));

        btnFetch.setBackground(new java.awt.Color(0, 51, 255));
        btnFetch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFetch.setForeground(new java.awt.Color(255, 255, 255));
        btnFetch.setText("Fetch Data");
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });
        jPanel1.add(btnFetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String movieName = edtMovie.getText();
        String actorName = edtActor.getText();
        String actressName = edtActress.getText();
        String directorName = edtDirector.getText();
        String releaseYear = edtRelease.getText();
        
        //Insert the Data
        insert(movieName, actorName, actressName, directorName, releaseYear);
    }//GEN-LAST:event_submitActionPerformed

    //Place Holder Functionality Start
    private void edtMovieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtMovieFocusGained
        // TODO add your handling code here:
        if(edtMovie.getText().trim().equals("Enter Movie Name")){
            edtMovie.setText("");
        }
    }//GEN-LAST:event_edtMovieFocusGained

    private void edtMovieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtMovieFocusLost
        // TODO add your handling code here:
        if(edtMovie.getText().trim().equals("")){
            edtMovie.setText("Enter Movie Name");
        }
    }//GEN-LAST:event_edtMovieFocusLost

    private void edtActorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtActorFocusGained
        // TODO add your handling code here:
        if(edtActor.getText().trim().equals("Enter Actor Name")){
            edtActor.setText("");
        }
    }//GEN-LAST:event_edtActorFocusGained

    private void edtActorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtActorFocusLost
        // TODO add your handling code here:
        if(edtActor.getText().trim().equals("")){
            edtActor.setText("Enter Actor Name");
        }
    }//GEN-LAST:event_edtActorFocusLost

    private void edtActressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtActressFocusGained
        // TODO add your handling code here:
        if(edtActress.getText().trim().equals("Enter Actress Name")){
            edtActress.setText("");
        }
    }//GEN-LAST:event_edtActressFocusGained

    private void edtActressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtActressFocusLost
        // TODO add your handling code here:
        if(edtActress.getText().trim().equals("")){
            edtActress.setText("Enter Actress Name");
        }
    }//GEN-LAST:event_edtActressFocusLost

    private void edtDirectorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtDirectorFocusGained
        // TODO add your handling code here:
        if(edtDirector.getText().trim().equals("Enter Director Name")){
            edtDirector.setText("");
        }
    }//GEN-LAST:event_edtDirectorFocusGained

    private void edtDirectorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtDirectorFocusLost
        // TODO add your handling code here:
        if(edtDirector.getText().trim().equals("")){
            edtDirector.setText("Enter Director Name");
        }
    }//GEN-LAST:event_edtDirectorFocusLost

    private void edtReleaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtReleaseFocusGained
        // TODO add your handling code here:
        if(edtRelease.getText().trim().equals("Enter Release Year")){
            edtRelease.setText("");
        }
    }//GEN-LAST:event_edtReleaseFocusGained

    private void edtReleaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtReleaseFocusLost
        // TODO add your handling code here:
        if(edtRelease.getText().trim().equals("")){
            edtRelease.setText("Enter Release Year");
        }
    }//GEN-LAST:event_edtReleaseFocusLost
    // Place Holder Functionality End
    
    //Fetch Data
    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
        // TODO add your handling code here:
        fetchData();
    }//GEN-LAST:event_btnFetchActionPerformed
    
    //Insert Function
    void insert(String movieName, String actorName, String actressName, String directorName, String releaseYear) {
        try {
           //1 Load JDBC driver
           Class.forName("com.mysql.jdbc.Driver");

           //2 Define Connnection URL
           String mysqlURL = "jdbc:mysql://localhost:3306/movieslist?user=root";

           //3 Establish Connection
           Connection conn = DriverManager.getConnection(mysqlURL);

           //4 Create a preparedStatement object
           //? shows parameterized query
           String sql = "INSERT INTO movie(movieName, actorName, actressName, directorName, releaseYear) VALUES(?, ?, ?, ?, ?)"; 
           
           PreparedStatement mov = conn.prepareStatement(sql);
           mov.setString(1, movieName);
           mov.setString(2, actorName);
           mov.setString(3, actressName);
           mov.setString(4, directorName);
           mov.setString(5, releaseYear);
           
           //5 Exectue a query
           int rowsInserted = mov.executeUpdate();
           JOptionPane.showMessageDialog(this, "Record inserted : " + rowsInserted);

           //6 Close the connection
           conn.close();
           
           //To reset the values after inserted
           reset();
           
        } catch (ClassNotFoundException ex) {
            System.out.println("Error Loading Driver" + ex);
        } catch (SQLException ex) {
           System.out.println(ex);
        }
    }
    // Reset value Function
    private void reset(){
        edtMovie.setText("Enter Movie Name");
        edtActor.setText("Enter Actor Name");
        edtActress.setText("Enter Actress Name");
        edtDirector.setText("Enter Director Name");
        edtRelease.setText("Enter Release Year");
    }
    //Fetch Data from Database
    public void fetchData(){
        try{
            //1 Load JDBC driver
           Class.forName("com.mysql.jdbc.Driver");

           //2 Define Connnection URL
           String mysqlURL = "jdbc:mysql://localhost:3306/movieslist?user=root";

           //3 Establish Connection
           Connection conn = DriverManager.getConnection(mysqlURL);

           //4 Create a preparedStatement object
           PreparedStatement pst= conn.prepareStatement("SELECT * FROM movie");
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData movieData = rs.getMetaData();
           
           int colCount = movieData.getColumnCount();
           DefaultTableModel recordTable = (DefaultTableModel)jTable1.getModel();
           recordTable.setRowCount(0);
           while(rs.next()){
               Vector colData = new Vector();
               for (int i=1; i<=colCount; i++){
                   colData.add(i);
                   colData.add(rs.getString("movieName"));
                   colData.add(rs.getString("actorName"));
                   colData.add(rs.getString("actressName"));
                   colData.add(rs.getString("directorName"));
                   colData.add(rs.getString("releaseYear"));
               }
               recordTable.addRow(colData);
           }
        } catch(Exception e){ System.out.println(e);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFetch;
    private javax.swing.JTextField edtActor;
    private javax.swing.JTextField edtActress;
    private javax.swing.JTextField edtDirector;
    private javax.swing.JTextField edtMovie;
    private javax.swing.JTextField edtRelease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
